services:
  rag-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: rag-microservice-api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      # For development - mount source code for live reload
      - ../src:/app/src
      - ../streamlit:/app/streamlit
      - ../data:/app/data
      - ../logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - VECTOR_STORE_PERSIST_DIRECTORY=/app/data/chromadb    
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]    
    networks:
      - rag-network

  # Streamlit UI Service
  rag-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    container_name: rag-microservice-ui
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - API_URL=http://rag-api:8000
      - HEALTH_TIMEOUT=30
      - QUERY_TIMEOUT=300
    command: ["streamlit", "run", "streamlit/app.py", "--server.address", "0.0.0.0", "--server.port", "8501", "--server.headless", "true"]
    depends_on:
      - rag-api
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
