# Streamlit secrets configuration
# This file should not be committed to version control in production

[default]
API_URL = "http://localhost:8000"

# You can add other configuration here as needed
# [database]
# host = "localhost"
# port = 5432
# username = "user"
# password = "password"